"""initial tables

Revision ID: 17082fb841a9
Revises: 
Create Date: 2026-04-23 20:11:48.295929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17082fb841a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('company_db', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('UPLOAD', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('sap_module', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'FAILED', name='auditstatus'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_username'), 'audit_log', ['username'], unique=False)
    op.create_table('upload_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('company_db', sa.String(length=50), nullable=False),
    sa.Column('sap_module', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_batch_sap_module'), 'upload_batch', ['sap_module'], unique=False)
    op.create_index(op.f('ix_upload_batch_username'), 'upload_batch', ['username'], unique=False)
    op.create_table('upload_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.Enum('VALIDATION', 'SAP', name='errortype'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_error_batch_id'), 'upload_error', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_error_batch_id'), table_name='upload_error')
    op.drop_table('upload_error')
    op.drop_index(op.f('ix_upload_batch_username'), table_name='upload_batch')
    op.drop_index(op.f('ix_upload_batch_sap_module'), table_name='upload_batch')
    op.drop_table('upload_batch')
    op.drop_index(op.f('ix_audit_log_username'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
